DATASET:
    NAME: "grounded_id2"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    WORKERS: 8
TRAIN:
    EPOCHS: 150
    BATCH_SIZE: 4
    CROP_SIZE: (512, 512)
    BASE_SIZE: 512
    BACKBONE_PRETRAINED_PATH: "pretrained/pvt_medium.pth"
    MODEL_SAVE_DIR: '/data/MichaelWang/checkpoints/Grounded_ID2/pvt_medium_FPT'
    APEX: True
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (512, 512)
    TEST_MODEL_PATH: "/data/MichaelWang/checkpoints/Grounded_ID2/5to5_pvt_medium_FPT/115.pth"

SOLVER:
    OPTIMIZER: "adamw"
    LR: 0.0001
MODEL:
    MODEL_NAME: "PVT_FPT"
    BACKBONE: "pvt_medium"


AUG:
    CROP: False
