DATASET:
    NAME: "transparent11"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    WORKERS: 8

DATASET2:
    NAME: "stanford2d3d"

TRAIN:
    EPOCHS: 100
    ITERS: 20000
    BATCH_SIZE: 4
    CROP_SIZE: (512, 512)
    BASE_SIZE: 512
    BACKBONE_PRETRAINED_PATH: "pretrained/pvt_small.pth"
    MODEL_SAVE_DIR: 'workdirs/joint_stan_trans/pvt_small_FPT64'
    APEX: True
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (512, 512)

SOLVER:
    OPTIMIZER: "adamw"
    LR: 0.0001
MODEL:
    MODEL_NAME: "PVT_FPT_JOINT"
    BACKBONE: "pvt_small"

AUG:
    CROP: False
