DATASET:
    NAME: "acdc"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    WORKERS: 8
TRAIN:
    EPOCHS: 200
    BATCH_SIZE: 4
    CROP_SIZE: (512, 512)
    BASE_SIZE: 512
    BACKBONE_PRETRAINED_PATH: "pretrained/pvt_tiny.pth"
    MODEL_SAVE_DIR: 'workdirs/acdc/pvt_tiny_FPT'
    APEX: True
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (512, 512)
    TEST_MODEL_PATH: 'workdirs/acdc/pvt_small_FPT/best_model.pth'

SOLVER:
    OPTIMIZER: "adamw"
    LR: 0.0001
MODEL:
    MODEL_NAME: "PVT_FPT"
    BACKBONE: "pvt_tiny"
    EMB_CHANNELS: 64

AUG:
    CROP: True
