DATASET:
    NAME: "acdc"
    MEAN: [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    WORKERS: 8
TRAIN:
    EPOCHS: 200
    BATCH_SIZE: 12
    CROP_SIZE: (512,512)
    BASE_SIZE: 512
    BACKBONE_PRETRAINED_PATH: "pretrained/mit_b1.pth"
    MODEL_SAVE_DIR: 'workdirs/acdc/pvtv2_mit_b1_FPT'
    APEX: True
TEST:
    BATCH_SIZE: 4
    CROP_SIZE: (512,512)
    TEST_MODEL_PATH: 'workdirs/acdc/pvtv2_mit_b1_FPT/best_model.pth'

SOLVER:
    OPTIMIZER: "adamw"
    LR: 0.00005
MODEL:
    MODEL_NAME: "PVTV2_MIT_FPT"
    BACKBONE: "mit_b1"
    EMB_CHANNELS: 64

AUG:
    CROP: True
